import { z } from 'zod';
import { COMPONENT_FILE_TYPES, COMPONENT_TIERS, USER_ROLES } from './types';

/**
 * Runtime contract for every payload that crosses an admin API boundary.
 * Nothing reaches Supabase without passing through one of these schemas.
 */

/** Lowercase, URL-safe, hyphen-separated identifier. */
export const slugSchema = z
  .string()
  .min(3, 'Slug must be at least 3 characters')
  .max(64, 'Slug must be at most 64 characters')
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/u, 'Slug must be lowercase alphanumeric words separated by single hyphens');

export const semverSchema = z
  .string()
  .regex(/^\d+\.\d+\.\d+$/u, 'Version must be a three-part semantic version, e.g. 1.0.0');

/** Rejects absolute paths, traversal segments, Windows drives and odd characters. */
export const filePathSchema = z
  .string()
  .min(3)
  .max(200)
  .regex(/^[A-Za-z0-9._\-/]+$/u, 'File path may only contain letters, numbers, dots, dashes, underscores and slashes')
  .refine((value) => !value.startsWith('/'), 'File path must be relative')
  .refine((value) => !value.includes('..'), 'File path must not contain traversal segments')
  .refine((value) => !/^[A-Za-z]:/u.test(value), 'File path must not be an absolute Windows path')
  .refine((value) => !value.includes('//'), 'File path must not contain empty segments');

export const componentTierSchema = z.enum(COMPONENT_TIERS);
export const componentFileTypeSchema = z.enum(COMPONENT_FILE_TYPES);
export const userRoleSchema = z.enum(USER_ROLES);

export const componentPropSchema = z.object({
  name: z
    .string()
    .min(1)
    .max(64)
    .regex(/^[A-Za-z_$][A-Za-z0-9_$]*$/u, 'Prop name must be a valid JavaScript identifier'),
  type: z.enum(['string', 'number', 'boolean', 'enum', 'node', 'object', 'array']),
  required: z.boolean().default(false),
  default: z.union([z.string(), z.number(), z.boolean(), z.null()]).optional(),
  description: z.string().max(280).optional(),
  options: z.array(z.string().min(1)).max(32).optional()
});

/** Hard ceiling per file so a single upload cannot exhaust database storage. */
const MAX_FILE_BYTES = 128 * 1024;
const MAX_FILES_PER_BUNDLE = 25;

export const componentFileSchema = z.object({
  filePath: filePathSchema,
  fileType: componentFileTypeSchema.default('SOURCE'),
  content: z
    .string()
    .min(1, 'File content must not be empty')
    .refine((value) => Buffer.byteLength(value, 'utf8') <= MAX_FILE_BYTES, {
      message: 'File content exceeds the 128 KB per-file limit'
    })
});

/** npm dependency map, e.g. `{ "lucide-react": "^0.300.0" }`. */
export const npmDependencyMapSchema = z.record(
  z
    .string()
    .min(1)
    .regex(/^(?:@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*$/u, 'Invalid npm package name'),
  z.string().min(1).max(32)
);

/**
 * Administrators upload one JSON document per component version. The shape is
 * intentionally flat so it can be authored by hand, exported by the CLI or
 * generated by an AI agent without a WYSIWYG editor.
 */
export const componentBundleSchema = z
  .object({
    slug: slugSchema,
    name: z.string().min(2).max(120),
    description: z.string().min(1).max(500),
    category: z.string().min(2).max(64),
    tier: componentTierSchema,
    version: semverSchema.default('1.0.0'),
    /**
     * Either the shorthand `{ "pkg": "^1.0.0" }` map or the explicit
     * `{ npm: {...}, internal: [...] }` form.
     */
    dependencies: z
      .union([
        npmDependencyMapSchema,
        z.object({
          npm: npmDependencyMapSchema.default({}),
          internal: z.array(z.string().min(1).max(64)).max(50).default([])
        })
      ])
      .default({}),
    propsSchema: z.array(componentPropSchema).max(50).default([]),
    files: z.array(componentFileSchema).min(1, 'A bundle must declare at least one file').max(MAX_FILES_PER_BUNDLE)
  })
  .strict()
  .superRefine((bundle, ctx) => {
    const seen = new Set<string>();
    bundle.files.forEach((file, index) => {
      const key = file.filePath.toLowerCase();
      if (seen.has(key)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['files', index, 'filePath'],
          message: `Duplicate file path: ${file.filePath}`
        });
      }
      seen.add(key);
    });

    if (!bundle.files.some((file) => file.fileType === 'SOURCE')) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['files'],
        message: 'A bundle must declare at least one SOURCE file'
      });
    }

    const propNames = new Set<string>();
    bundle.propsSchema.forEach((prop, index) => {
      if (propNames.has(prop.name)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['propsSchema', index, 'name'],
          message: `Duplicate prop name: ${prop.name}`
        });
      }
      propNames.add(prop.name);

      if (prop.type === 'enum' && (prop.options === undefined || prop.options.length === 0)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['propsSchema', index, 'options'],
          message: 'Enum props must declare at least one option'
        });
      }
    });
  });

export type ComponentBundleInput = z.input<typeof componentBundleSchema>;
export type ComponentBundle = z.output<typeof componentBundleSchema>;

/** Normalises either accepted dependency shape into the stored representation. */
export function normaliseDependencies(dependencies: ComponentBundle['dependencies']): {
  npm: Record<string, string>;
  internal: string[];
} {
  if ('npm' in dependencies && typeof dependencies.npm === 'object') {
    const explicit = dependencies as { npm: Record<string, string>; internal: string[] };
    return { npm: explicit.npm, internal: explicit.internal };
  }
  return { npm: dependencies as Record<string, string>, internal: [] };
}

export const publishActionSchema = z
  .object({
    componentId: z.string().uuid('componentId must be a UUID'),
    isPublished: z.boolean()
  })
  .strict();

export type PublishActionInput = z.infer<typeof publishActionSchema>;

export const profileUpdateSchema = z
  .object({
    isPremium: z.boolean().optional(),
    role: userRoleSchema.optional()
  })
  .strict()
  .refine(
    (value) => value.isPremium !== undefined || value.role !== undefined,
    'Provide at least one of isPremium or role'
  );

export type ProfileUpdateInput = z.infer<typeof profileUpdateSchema>;

export const uuidSchema = z.string().uuid();

/** Parses an untrusted string as a component bundle, surfacing readable errors. */
export function parseComponentBundleJson(raw: string): ComponentBundle {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw) as unknown;
  } catch {
    throw new SyntaxError('Payload is not valid JSON');
  }
  return componentBundleSchema.parse(parsed);
}

/** Flattens a Zod error into `field -> message` pairs for API responses. */
export function formatZodIssues(error: z.ZodError): Array<{ path: string; message: string }> {
  return error.issues.map((issue) => ({
    path: issue.path.length > 0 ? issue.path.join('.') : '(root)',
    message: issue.message
  }));
}
